# -*- coding: utf-8 -*-
"""Week-8.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17f3X2SQpr5BydfO55XlD5FYfydaCKJ3C
"""

import streamlit as st

def find_largest_number(a, b, c):
    return max(a, b, c)

def main():
    st.title("Find the Largest Number")

    a = st.number_input("Enter the first number:")
    b = st.number_input("Enter the second number:")
    c = st.number_input("Enter the third number:")

    if st.button("Find Largest"):
        largest = find_largest_number(a, b, c)
        st.success(f"The largest number is: {largest}")

if __name__ == "__main__":
    main()